import type {
  EnergyDocument,
  EnergyGraph,
  AnalysisResult,
  EnergyKPI,
} from "./types";

export const MOCK_DOCUMENTS: EnergyDocument[] = [
  {
    id: "doc_steg_bill_2025_10",
    name: "Facture STEG — Octobre 2025",
    doc_type: "steg_bill",
    date: "2025-10",
    zone: "global",
    energy_type: "electricity",
    quantity_kwh: 18634,
    unit_raw: "kWh",
    quantity_raw: 18634,
    amount_tnd: 2847.5,
    supplier: "STEG",
    facture_number: "69105258R",
    extraction_confidence: 0.97,
    extraction_method: "claude_vision",
    source_file: "WhatsApp Image 2025-10-28 (38).jpeg",
    added_at: "2025-11-01T09:00:00Z",
    anomalies: [
      {
        type: "RECONCILIATION",
        description: "Rapport Excel indique 19 100 kWh vs facture STEG 18 634 kWh (+2.5%)",
        value_observed: 19100,
        value_expected: 18634,
        delta_pct: 2.5,
        confidence_score: 0.96,
      },
    ],
    co2_kg: 11050,
    co2_scope: "scope2",
    fields: [
      { key: "date", label: "Mois", value: "10/2025" },
      { key: "active_energy_kwh", label: "Énergie Active", value: 18634, unit: "kWh", confidence: 0.99 },
      { key: "reactive_energy_kvarh", label: "Énergie Réactive", value: 4821, unit: "kVArh", confidence: 0.97 },
      { key: "power_subscribed_kva", label: "Puissance Souscrite", value: 1300, unit: "kVA", confidence: 1.0 },
      { key: "amount_tnd", label: "Net à Payer", value: 2847.5, unit: "TND", confidence: 0.98 },
      { key: "facture_number", label: "N° Facture", value: "69105258R", confidence: 1.0 },
      { key: "district", label: "District", value: "KRAM", confidence: 1.0 },
    ],
  },
  {
    id: "doc_meter_reading_2025_10",
    name: "Relevé Compteur — Octobre 2025",
    doc_type: "steg_meter_reading",
    date: "2025-10",
    zone: "global",
    energy_type: "electricity",
    quantity_kwh: 18634,
    unit_raw: "kWh",
    quantity_raw: 18634,
    amount_tnd: null,
    supplier: "STEG",
    extraction_confidence: 0.94,
    extraction_method: "claude_vision",
    source_file: "WhatsApp Image 2025-10-28 (39).jpeg",
    added_at: "2025-11-01T09:05:00Z",
    anomalies: [],
    co2_kg: null,
    co2_scope: null,
    fields: [
      { key: "date", label: "Mois", value: "Octobre 2025" },
      { key: "client_ref", label: "Réf Client", value: "226570", confidence: 1.0 },
      { key: "purchase_jour_kwh", label: "Achat Jour", value: 7200, unit: "kWh", confidence: 0.95 },
      { key: "purchase_nuit_kwh", label: "Achat Nuit", value: 5840, unit: "kWh", confidence: 0.93 },
      { key: "purchase_pointe_kwh", label: "Achat Pointe", value: 3980, unit: "kWh", confidence: 0.94 },
      { key: "purchase_soir_kwh", label: "Achat Soir", value: 4180, unit: "kWh", confidence: 0.94 },
      { key: "injection_total_kwh", label: "Injection Totale", value: 2566, unit: "kWh", confidence: 0.96 },
      { key: "net_consumption_kwh", label: "Net Consommé", value: 18634, unit: "kWh", confidence: 0.99 },
      { key: "purchase_reactive_kvarh", label: "Réactif Acheté", value: 4821, unit: "kVArh", confidence: 0.92 },
    ],
  },
  {
    id: "doc_excel_oct_2025",
    name: "Rapport Mensuel — Octobre 2025",
    doc_type: "excel_report",
    date: "2025-10",
    zone: "global",
    energy_type: "electricity",
    quantity_kwh: 19100,
    unit_raw: "kWh",
    quantity_raw: 19100,
    amount_tnd: null,
    extraction_confidence: 0.99,
    extraction_method: "pandas_excel",
    source_file: "octobre-report1_01112025.xlsx",
    added_at: "2025-11-02T08:00:00Z",
    anomalies: [
      {
        type: "RECONCILIATION",
        description: "Total zones (19 100) diffère de facture STEG (18 634 kWh) — écart 2.5%",
        value_observed: 19100,
        value_expected: 18634,
        delta_pct: 2.5,
        confidence_score: 0.96,
      },
    ],
    co2_kg: null,
    co2_scope: null,
    fields: [
      { key: "date", label: "Mois", value: "10/2025" },
      { key: "zone_alpha_kwh", label: "Zone Alpha — Élec.", value: 7200, unit: "kWh", confidence: 1.0 },
      { key: "zone_beta_kwh", label: "Zone Beta — Élec.", value: 6100, unit: "kWh", confidence: 1.0 },
      { key: "zone_gamma_kwh", label: "Zone Gamma — Élec.", value: 5800, unit: "kWh", confidence: 1.0 },
      { key: "total_kwh", label: "Total Électricité", value: 19100, unit: "kWh", confidence: 1.0 },
      { key: "trigeneration_production_kwh", label: "Production Tri-gen", value: 8640, unit: "kWh", confidence: 0.99 },
      { key: "gas_alpha_nm3", label: "GN Zone Alpha (chaudière)", value: 1240, unit: "Nm³", confidence: 0.98 },
      { key: "gas_gamma_nm3", label: "GN Zone Gamma (chaudière)", value: 780, unit: "Nm³", confidence: 0.98 },
      { key: "gas_trigeneration_nm3", label: "GN Tri-generation", value: 6552, unit: "Nm³", confidence: 0.99 },
    ],
  },
  {
    id: "doc_excel_sept_2025",
    name: "Rapport Mensuel — Septembre 2025",
    doc_type: "excel_report",
    date: "2025-09",
    zone: "global",
    energy_type: "electricity",
    quantity_kwh: 17890,
    unit_raw: "kWh",
    quantity_raw: 17890,
    amount_tnd: null,
    extraction_confidence: 0.99,
    extraction_method: "pandas_excel",
    source_file: "septembre-report1_01102025.xlsx",
    added_at: "2025-10-01T08:00:00Z",
    anomalies: [],
    co2_kg: null,
    co2_scope: null,
    fields: [
      { key: "date", label: "Mois", value: "09/2025" },
      { key: "zone_alpha_kwh", label: "Zone Alpha — Élec.", value: 6800, unit: "kWh", confidence: 1.0 },
      { key: "zone_beta_kwh", label: "Zone Beta — Élec.", value: 5800, unit: "kWh", confidence: 1.0 },
      { key: "zone_gamma_kwh", label: "Zone Gamma — Élec.", value: 5290, unit: "kWh", confidence: 1.0 },
      { key: "total_kwh", label: "Total Électricité", value: 17890, unit: "kWh", confidence: 1.0 },
      { key: "trigeneration_production_kwh", label: "Production Tri-gen", value: 8320, unit: "kWh", confidence: 0.98 },
      { key: "gas_trigeneration_nm3", label: "GN Tri-generation", value: 6280, unit: "Nm³", confidence: 0.99 },
    ],
  },
  {
    id: "doc_steg_bill_2025_09",
    name: "Facture STEG — Septembre 2025",
    doc_type: "steg_bill",
    date: "2025-09",
    zone: "global",
    energy_type: "electricity",
    quantity_kwh: 17920,
    unit_raw: "kWh",
    quantity_raw: 17920,
    amount_tnd: 2740.8,
    supplier: "STEG",
    facture_number: "68921440R",
    extraction_confidence: 0.96,
    extraction_method: "claude_vision",
    source_file: "WhatsApp Image 2025-09-28 (22).jpeg",
    added_at: "2025-10-01T09:00:00Z",
    anomalies: [],
    co2_kg: 10627,
    co2_scope: "scope2",
    fields: [
      { key: "date", label: "Mois", value: "09/2025" },
      { key: "active_energy_kwh", label: "Énergie Active", value: 17920, unit: "kWh", confidence: 0.98 },
      { key: "reactive_energy_kvarh", label: "Énergie Réactive", value: 4612, unit: "kVArh", confidence: 0.96 },
      { key: "amount_tnd", label: "Net à Payer", value: 2740.8, unit: "TND", confidence: 0.97 },
      { key: "facture_number", label: "N° Facture", value: "68921440R", confidence: 1.0 },
    ],
  },
  {
    id: "doc_pdf_audit_data",
    name: "Fiche Relevé Énergie — Achat et Vente",
    doc_type: "pdf_report",
    date: "2025-10",
    zone: "global",
    energy_type: "electricity",
    quantity_kwh: 18634,
    unit_raw: "kWh",
    quantity_raw: 18634,
    amount_tnd: null,
    extraction_confidence: 0.88,
    extraction_method: "pdfplumber",
    source_file: "fiche releve donne .pdf",
    added_at: "2025-11-03T10:00:00Z",
    anomalies: [],
    co2_kg: null,
    co2_scope: null,
    fields: [
      { key: "date", label: "Mois", value: "Octobre 2025" },
      { key: "net_consumption", label: "Consommation Nette", value: 18634, unit: "kWh", confidence: 0.88 },
    ],
  },
];

export const MOCK_GRAPH: EnergyGraph = {
  nodes: [
    { id: "site_adwya", type: "site", label: "ADWYA", description: "Usine pharmaceutique, Sidi Daoud, Tunisia", position: { x: 500, y: 300 }, severity: "ok" },
    { id: "supplier_steg", type: "supplier", label: "STEG", description: "Société Tunisienne de l'Électricité et du Gaz\nHTA 30kV — District KRAM\nRéf. client: 226570", position: { x: 150, y: 300 }, severity: "ok" },
    { id: "zone_alpha", type: "zone", label: "Zone Alpha", description: "Fabrication + Chaudière vapeur MANGAZZINI 1240kW\n6 CTA — Distillateur EPPI", position: { x: 400, y: 100 }, severity: "ok" },
    { id: "zone_beta", type: "zone", label: "Zone Beta", description: "Conditionnement + Chaudière eau chaude VIADRUS 400kW\n5 CTA + Munters — AUCUNE récupération tri-gen", position: { x: 500, y: 500 }, severity: "warning" },
    { id: "zone_gamma", type: "zone", label: "Zone Gamma", description: "Stockage + Chaudière vapeur MANGAZZINI 600kW\nCTA R1 avec supervision", position: { x: 700, y: 120 }, severity: "ok" },
    { id: "equip_trigeneration", type: "equipment", label: "Tri-génération", description: "Moteur gaz + alternateur\n1200 kW électrique — 42-44% rendement\n1270 kW chaleur récupérable\nConsommation: 273 Nm³/h GN", position: { x: 280, y: 420 }, severity: "ok" },
    { id: "equip_absorption", type: "equipment", label: "Absorbeur THERMAX", description: "THERMAX TAC L5 E1\nNominal: 802 kWfg → Mesuré: 261 kW (32%!)\nCOP: 74% — Eau glacée 6-12°C", position: { x: 280, y: 580 }, severity: "critical", anomaly: true },
    { id: "equip_compressor", type: "equipment", label: "Compresseur D132RS-8A", description: "KOMPRESSOR D132RS-8A — 2022\n132 kW — 22.95 m³/min\nTaux de charge moyen: 39%\n15 362h sur 17 510h à <20% charge", position: { x: 700, y: 420 }, severity: "warning", anomaly: true },
    { id: "equip_boiler_alpha", type: "equipment", label: "Chaudière Vapeur Alpha", description: "MANGAZZINI PVR 15 — 1240 kW\nRiello RS130 — 2 T/h\nCompteur vapeur: installé mais NON branché au GTE", position: { x: 250, y: 130 }, severity: "warning", anomaly: true },
    { id: "equip_boiler_gamma", type: "equipment", label: "Chaudière Vapeur Gamma", description: "MANGAZZINI PVR 5 EU — 600 kW\nRiello RS44 — 1 T/h\nCompteur vapeur: installé mais NON branché au GTE", position: { x: 800, y: 200 }, severity: "warning", anomaly: true },
    { id: "equip_geg_alpha", type: "equipment", label: "GEG1+2 Alpha", description: "Carrier 30XA0402 (391kW, EER 3.11)\n+ Carrier 30XA0252 (274kW, EER 3.05)\nTotal: 665 kW frigorifiques", position: { x: 420, y: 0 }, severity: "ok" },
    { id: "equip_boiler_beta", type: "equipment", label: "Chaudière Eau Chaude Beta", description: "VIADRUS G700 — 400 kW — 2019\nPAS de récupération tri-gen prévue\nBrûle du gaz pur alors que 1270 kW disponibles", position: { x: 620, y: 550 }, severity: "critical", anomaly: true },
    { id: "meter_ctr3738835", type: "meter", label: "Compteur Achat STEG", description: "CTR 3738835 — Compteur MT\nMesure: énergie active + réactive + FP", position: { x: 150, y: 150 }, severity: "ok" },
    { id: "meter_gn_general", type: "meter", label: "Compteur GN Général", description: "Compteur général GN + correcteur numérique\nTarif BP2 — Débit souscrit 6000 th/h", position: { x: 150, y: 450 }, severity: "ok" },
    { id: "meter_gn_beta_munters", type: "meter", label: "Compteur GN Beta+Munters", description: "COMPTEUR PARTAGÉ: chaudière Beta + Munters\nIMPOSSIBLE de séparer les consommations\nRecommandation: installer sous-compteurs dédiés", position: { x: 620, y: 650 }, severity: "critical", anomaly: true },
    { id: "meter_steam_alpha", type: "meter", label: "Compteur Vapeur Alpha", description: "Compteur vapeur installé — NON branché au GTE\nDonnées vapor non disponibles dans les rapports", position: { x: 250, y: 50 }, severity: "critical", anomaly: true },
    { id: "doc_bill_oct", type: "document", label: "Facture STEG Oct 2025", description: "18 634 kWh — 2 847.5 TND\nConfiance: 97% — Claude Vision", position: { x: 0, y: 300 }, documentId: "doc_steg_bill_2025_10", severity: "warning", anomaly: true },
    { id: "doc_excel_oct", type: "document", label: "Rapport Excel Oct 2025", description: "Alpha: 7200 + Beta: 6100 + Gamma: 5800 = 19 100 kWh\nÉcart vs facture: +2.5%", position: { x: 0, y: 420 }, documentId: "doc_excel_oct_2025", severity: "warning", anomaly: true },
    { id: "anom_reconciliation_oct", type: "anomaly", label: "Écart Octobre 2025", description: "RÉCONCILIATION: Excel 19 100 kWh vs STEG 18 634 kWh\nÉcart: +466 kWh (+2.5%)\nSource probable: lag de mesure ou erreur rapport", position: { x: 0, y: 510 }, severity: "critical", anomaly: true },
    { id: "anom_absorption_underperf", type: "anomaly", label: "Absorbeur Sous-performant", description: "Puissance nominale: 802 kW\nPuissance mesurée: 261 kW (32%)\nPerte: ~541 kW non récupérés", position: { x: 180, y: 650 }, severity: "critical", anomaly: true },
    { id: "anom_compressor_oversize", type: "anomaly", label: "Compresseur Surdimensionné", description: "Taux de charge moyen: 39%\n15 362h / 17 510h à charge 0-20%\nÉnergie gaspillée: ~80% de 132 kW", position: { x: 850, y: 480 }, severity: "warning", anomaly: true },
  ],
  edges: [
    { id: "e1", source: "supplier_steg", target: "site_adwya", type: "supplies", label: "HTA 30kV" },
    { id: "e2", source: "zone_alpha", target: "site_adwya", type: "part_of" },
    { id: "e3", source: "zone_beta", target: "site_adwya", type: "part_of" },
    { id: "e4", source: "zone_gamma", target: "site_adwya", type: "part_of" },
    { id: "e5", source: "equip_trigeneration", target: "site_adwya", type: "located_in" },
    { id: "e6", source: "equip_absorption", target: "equip_trigeneration", type: "feeds", label: "chaleur récupérée" },
    { id: "e7", source: "equip_trigeneration", target: "site_adwya", type: "feeds", label: "1200 kW élec" },
    { id: "e8", source: "equip_boiler_alpha", target: "zone_alpha", type: "located_in" },
    { id: "e9", source: "equip_boiler_gamma", target: "zone_gamma", type: "located_in" },
    { id: "e10", source: "equip_geg_alpha", target: "zone_alpha", type: "located_in" },
    { id: "e11", source: "equip_boiler_beta", target: "zone_beta", type: "located_in" },
    { id: "e12", source: "equip_compressor", target: "site_adwya", type: "located_in" },
    { id: "e13", source: "meter_ctr3738835", target: "site_adwya", type: "measured_by" },
    { id: "e14", source: "meter_gn_general", target: "equip_trigeneration", type: "measured_by" },
    { id: "e15", source: "meter_gn_beta_munters", target: "equip_boiler_beta", type: "shared_with", label: "PARTAGÉ" },
    { id: "e16", source: "meter_steam_alpha", target: "equip_boiler_alpha", type: "measured_by" },
    { id: "e17", source: "meter_steam_alpha", target: "site_adwya", type: "not_connected_to", label: "NON branché GTE" },
    { id: "e18", source: "doc_bill_oct", target: "meter_ctr3738835", type: "extracted_from" },
    { id: "e19", source: "doc_excel_oct", target: "site_adwya", type: "extracted_from" },
    { id: "e20", source: "anom_reconciliation_oct", target: "doc_bill_oct", type: "discrepancy" },
    { id: "e21", source: "anom_reconciliation_oct", target: "doc_excel_oct", type: "discrepancy" },
    { id: "e22", source: "anom_absorption_underperf", target: "equip_absorption", type: "discrepancy" },
    { id: "e23", source: "anom_compressor_oversize", target: "equip_compressor", type: "discrepancy" },
    { id: "e24", source: "equip_trigeneration", target: "zone_alpha", type: "feeds", label: "chaleur 300kW" },
    { id: "e25", source: "equip_trigeneration", target: "zone_gamma", type: "feeds", label: "chaleur 600kW" },
  ],
};

export const MOCK_ANALYSIS: AnalysisResult[] = [
  {
    id: "an_001",
    type: "reconciliation",
    title: "Écart de réconciliation — Octobre 2025",
    content: "Le rapport Excel mensuel indique une consommation totale de 19 100 kWh (Alpha: 7200 + Beta: 6100 + Gamma: 5800), tandis que la facture STEG pour la même période affiche 18 634 kWh. L'écart de 466 kWh (+2.5%) dépasse le seuil de tolérance de 2%. Source probable: lag de lecture de compteur ou erreur de saisie dans le rapport. Vérifier les index CTR 3738835 pour le mois d'octobre.",
    severity: "critical",
    date: "2025-10",
    value: 2.5,
    unit: "%",
    document_ids: ["doc_steg_bill_2025_10", "doc_excel_oct_2025"],
    created_at: "2025-11-05T10:00:00Z",
  },
  {
    id: "an_002",
    type: "anomaly",
    title: "Absorbeur THERMAX — Sous-performance critique",
    content: "La machine à absorption THERMAX TAC L5 E1 présente une puissance mesurée de 261 kW, soit seulement 32% de sa capacité nominale de 802 kWfg. Sur 6 mois de mesure (2024-2025), la moyenne est de 258-261 kW. Causes probables: régulation V3V mal calibrée, encrassement des échangeurs, ou déréglage du thermostat d'eau glacée. Impact: ~541 kW de froid non produit — remplacé par les GEG électriques à ~170 kW électrique supplémentaires/heure.",
    severity: "critical",
    date: "2025-10",
    value: 32,
    unit: "% nominal",
    document_ids: [],
    created_at: "2025-11-05T10:05:00Z",
  },
  {
    id: "an_003",
    type: "anomaly",
    title: "Compresseur KOMPRESSOR D132RS-8A — Surdimensionnement",
    content: "Le compresseur principal a fonctionné à moins de 20% de charge pendant 15 362 des 17 510 heures en charge (87.7% du temps). Débit moyen mesuré: 9 m³/min vs capacité installée 22.95 m³/min (39% de taux de charge moyen). À ce niveau, le rendement énergétique est particulièrement faible — environ 80% de l'énergie électrique consommée (132 kW) est perdue en chaleur. Recommandation: évaluer le remplacement par un compresseur de 75-90 kW avec VEV.",
    severity: "warning",
    date: "2025-10",
    value: 39,
    unit: "% charge",
    document_ids: [],
    created_at: "2025-11-05T10:10:00Z",
  },
  {
    id: "an_004",
    type: "anomaly",
    title: "Zone Beta — Absence de récupération Tri-génération",
    content: "La chaufferie Beta (VIADRUS G700, 400 kW) ne bénéficie d'aucune connexion au circuit de récupération de la tri-génération, contrairement aux zones Alpha et Gamma. La tri-génération produit 1 270 kW de chaleur récupérable mais la zone Beta continue de brûler du gaz naturel de façon autonome. La consommation GN de Beta est également impossible à isoler car le compteur est partagé avec les Munters. Recommandation: installer un échangeur à plaques côté Beta + sous-compteur GN dédié.",
    severity: "critical",
    date: "2025-10",
    value: 400,
    unit: "kW non récupérés",
    document_ids: [],
    created_at: "2025-11-05T10:15:00Z",
  },
  {
    id: "an_005",
    type: "anomaly",
    title: "Compteurs Vapeur — Non connectés au GTE",
    content: "Les deux compteurs vapeur des chaudières MANGAZZINI (Zone Alpha et Zone Gamma) sont physiquement installés mais non connectés au système de gestion technique (GTE). Les données de consommation vapeur ne remontent donc pas dans les rapports mensuels. Cela crée un angle mort énergétique significatif sur un vecteur consommant jusqu'à 1 840 kW thermiques combinés. Les purges vapeur (3-5% de pertes) et les condensats non récupérés restent également non mesurés.",
    severity: "warning",
    date: "2025-10",
    value: null as unknown as number,
    unit: undefined,
    document_ids: [],
    created_at: "2025-11-05T10:20:00Z",
  },
  {
    id: "an_006",
    type: "co2_estimate",
    title: "Bilan CO₂ — Octobre 2025",
    content: "Scope 2 (électricité réseau): 18 634 kWh × 0.593 kgCO₂/kWh = 11 050 kgCO₂\nScope 1 — Tri-génération: 6 552 Nm³ × 9.51 kWh/Nm³ × 0.201 kgCO₂/kWh = 12 534 kgCO₂\nScope 1 — Chaudières (Alpha+Gamma): (1 240+780) Nm³ × 9.51 × 0.201 = 3 862 kgCO₂\nCrédit injection: 2 566 kWh × 0.593 = -1 522 kgCO₂\n\nTotal brut: 25 924 kgCO₂ | Total net: 25 924 – 1 522 = 24 402 kgCO₂\n\nBénéfice tri-génération: la tri-gen produit 8 640 kWh élec + 1 270 kW chaleur × 720h = 915 840 kWh_th récupérés → CO₂ évité: ~23 000 kgCO₂/mois vs achat réseau pur.",
    severity: "ok",
    date: "2025-10",
    value: 24402,
    unit: "kgCO₂",
    document_ids: ["doc_steg_bill_2025_10", "doc_excel_oct_2025"],
    created_at: "2025-11-05T10:25:00Z",
  },
  {
    id: "an_007",
    type: "kpi",
    title: "KPI ISO 50001 — Octobre 2025",
    content: "Facteur de puissance: kWh / √(kWh² + kVArh²) = 18634 / √(18634² + 4821²) = 0.968 ✓ (seuil STEG: 0.90)\nAuto-suffisance électrique: production tri-gen / total consommé = 8640 / (18634 + 8640) = 31.7%\nDépendance réseau: 68.3%\nIntensité CO₂: 24 402 kgCO₂ / 27 274 kWh_total = 0.895 kgCO₂/kWh\nIndice de performance énergétique (EnPI): 1.07 (légèrement au-dessus de la baseline sur 12 mois)",
    severity: "ok",
    date: "2025-10",
    value: 0.968,
    unit: "cos φ",
    document_ids: ["doc_steg_bill_2025_10"],
    created_at: "2025-11-05T10:30:00Z",
  },
];

export const MOCK_KPIS: EnergyKPI[] = [
  { label: "Facteur de Puissance", value: "0.968", unit: "cos φ", status: "ok", description: "Cible STEG: >0.90 — Pénalité réactive évitée" },
  { label: "Auto-suffisance Élec.", value: "31.7", unit: "%", status: "ok", description: "Production tri-gen / consommation totale" },
  { label: "Dépendance Réseau", value: "68.3", unit: "%", status: "warning", description: "Part de l'électricité achetée à STEG" },
  { label: "CO₂ net (Oct 2025)", value: "24 402", unit: "kgCO₂", status: "ok", description: "Scope 1 + Scope 2, crédit injection déduit" },
  { label: "Intensité CO₂", value: "0.895", unit: "kgCO₂/kWh", status: "warning", description: "Total CO₂ / total énergie consommée" },
  { label: "EnPI (Indice Perf.)", value: "1.07", unit: "", status: "warning", description: "Consommation réelle / baseline 12 mois (>1 = dégradation)" },
  { label: "Absorbeur THERMAX", value: "32", unit: "% nominal", status: "critical", description: "261 kW mesurés vs 802 kW nominaux — anomalie critique" },
  { label: "Charge Compresseur", value: "39", unit: "%", status: "warning", description: "Compresseur chroniquement sous-sollicité" },
];
